/**
 * **The summary across every run** (`experiment/README.md`): reads the six
 * corpus analyses (`results*.json`, `results*.csv`) and the three harness
 * experiments (`servicing-jev*.experiment-result.json`), and writes
 * `experiment/SUMMARY.md` — the master tables a report quotes, with the
 * paired q1-against-q2 tests computed from the per-row CSVs. No call.
 *
 *     node scripts/summary.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';

interface Rate {
	k: number;
	n: number;
	rate: number;
	ci: [number, number];
}
interface QuestionResult {
	n: number;
	regex: Rate;
	jev: Rate;
	uncontested: { regex: Rate; jev: Rate };
	jevEitherLabeller: Rate;
	calibration: { ece: number; brier: number };
	gates: { threshold: number; toPerson: Rate; autoAccuracy: Rate; endToEnd: Rate }[];
}
interface Detection {
	tp: number;
	fn: number;
	fp: number;
	tn: number;
	recall: Rate;
	precision: Rate;
}
interface Results {
	corpus: string;
	questions: string;
	rows: number;
	contested: number;
	calls: number;
	byQuestion: { category: QuestionResult; need: QuestionResult };
	detection: { regex: Detection; jev: Detection };
	steer?: Detection & { threshold: number };
	latencyMs: { p50: number; p95: number; max: number };
	inputTokens: { mean: number; total: number };
	costUsd: { total: number; perCase: number };
}

const RUNS: { corpus: string; questions: string; file: string; note: string }[] = [
	{ corpus: 'v1', questions: 'q1', file: 'results', note: 'first run' },
	{ corpus: 'v2', questions: 'q1', file: 'results-v2', note: 'harder data' },
	{ corpus: 'v3', questions: 'q1', file: 'results-v3-q1', note: 'held out' },
	{ corpus: 'v3', questions: 'q2', file: 'results-v3-q2', note: 'held out — the test of q2' },
	{ corpus: 'v1', questions: 'q2', file: 'results-v1-q2', note: 'regression check' },
	{ corpus: 'v2', questions: 'q2', file: 'results-v2-q2', note: 'seen: q2 was written from v2' }
];

const load = (file: string) =>
	JSON.parse(readFileSync(`experiment/${file}.json`, 'utf8')) as Results;
const pct = (r: Rate) => `${(100 * r.rate).toFixed(0)}%`;
const ci = (r: Rate) =>
	r.n === 0
		? '—'
		: `${(100 * r.rate).toFixed(0)}% (${r.k}/${r.n}; ${(100 * r.ci[0]).toFixed(0)}–${(100 * r.ci[1]).toFixed(0)})`;

// ── Per-row CSVs, for the paired tests ─────────────────────────────────

function parseCsv(text: string): string[][] {
	const rows: string[][] = [];
	let row: string[] = [];
	let cell = '';
	let quoted = false;
	for (let i = 0; i < text.length; i += 1) {
		const c = text[i]!;
		if (quoted) {
			if (c === '"' && text[i + 1] === '"') {
				cell += '"';
				i += 1;
			} else if (c === '"') quoted = false;
			else cell += c;
		} else if (c === '"') quoted = true;
		else if (c === ',') {
			row.push(cell);
			cell = '';
		} else if (c === '\n') {
			row.push(cell);
			rows.push(row);
			row = [];
			cell = '';
		} else cell += c;
	}
	return rows;
}

function rightByRow(file: string, question: string): Map<string, boolean> {
	const [header, ...rows] = parseCsv(readFileSync(`experiment/${file}.csv`, 'utf8'));
	const at = (name: string) => header!.indexOf(name);
	return new Map(
		rows
			.filter((row) => row[at('question')] === question)
			.map((row) => [row[at('row')]!, row[at('jev_right')] === '1'])
	);
}

const choose = (n: number, k: number) => {
	let c = 1;
	for (let i = 0; i < k; i += 1) c = (c * (n - i)) / (i + 1);
	return c;
};

/** Exact two-sided sign test (McNemar) over the discordant pairs. */
function paired(before: string, after: string, question: string) {
	const a = rightByRow(before, question);
	const b = rightByRow(after, question);
	let fixed = 0;
	let broken = 0;
	for (const [row, right] of a) {
		const now = b.get(row)!;
		if (!right && now) fixed += 1;
		if (right && !now) broken += 1;
	}
	const n = fixed + broken;
	let tail = 0;
	for (let i = 0; i <= Math.min(fixed, broken); i += 1) tail += choose(n, i) / 2 ** n;
	return { fixed, broken, p: n === 0 ? 1 : Math.min(1, 2 * tail) };
}

// ── The summary ────────────────────────────────────────────────────────

const lines: string[] = [
	'# Jev on the servicing corpora — the summary across every run',
	'',
	'Generated by `node scripts/summary.ts` from the files beside it; every figure traces to `results*.json` / `results*.csv` or a `servicing-jev*.experiment-result.json`. Model `jev-1.13.0`, recorded 2026-09-28. Rates with Wilson 95% intervals.',
	'',
	'## 1. Accuracy by corpus and question set',
	'',
	'| corpus | questions | note | rows (contested) | request: regex | request: Jev | need: regex | need: Jev | need: Jev, uncontested |',
	'|---|---|---|---|---|---|---|---|---|'
];
const loaded = RUNS.map((run) => ({ ...run, r: load(run.file) }));
for (const { corpus, questions, note, r } of loaded) {
	const c = r.byQuestion.category;
	const n = r.byQuestion.need;
	lines.push(
		`| ${corpus} | ${questions} | ${note} | ${r.rows} (${r.contested}) | ${pct(c.regex)} | ${ci(c.jev)} | ${pct(n.regex)} | ${ci(n.jev)} | ${r.contested > 0 ? ci(n.uncontested.jev) : '—'} |`
	);
}

lines.push(
	'',
	'## 2. Vulnerability detection (any need recorded vs any need disclosed)',
	'',
	'| corpus | questions | regex recall | regex precision | Jev recall | Jev precision | Jev tp / fn / fp / tn |',
	'|---|---|---|---|---|---|---|'
);
for (const { corpus, questions, r } of loaded) {
	const x = r.detection.regex;
	const j = r.detection.jev;
	lines.push(
		`| ${corpus} | ${questions} | ${pct(x.recall)} | ${pct(x.precision)} | ${ci(j.recall)} | ${ci(j.precision)} | ${j.tp} / ${j.fn} / ${j.fp} / ${j.tn} |`
	);
}

lines.push(
	'',
	'## 3. Calibration of Jev',
	'',
	'| corpus | questions | request ECE | request Brier | need ECE | need Brier |',
	'|---|---|---|---|---|---|'
);
for (const { corpus, questions, r } of loaded) {
	const c = r.byQuestion.category.calibration;
	const n = r.byQuestion.need.calibration;
	lines.push(
		`| ${corpus} | ${questions} | ${c.ece.toFixed(3)} | ${c.brier.toFixed(3)} | ${n.ece.toFixed(3)} | ${n.brier.toFixed(3)} |`
	);
}

lines.push(
	'',
	'## 4. The gate at 0.80 and 0.90 (a person reviews below the threshold, or a steer under q2; the reviewer modelled as always right)',
	'',
	'| corpus | questions | threshold | request to a person | request end to end | need to a person | need end to end |',
	'|---|---|---|---|---|---|---|'
);
for (const { corpus, questions, r } of loaded) {
	for (const threshold of [0.8, 0.9]) {
		const c = r.byQuestion.category.gates.find((g) => g.threshold === threshold)!;
		const n = r.byQuestion.need.gates.find((g) => g.threshold === threshold)!;
		lines.push(
			`| ${corpus} | ${questions} | ${threshold.toFixed(2)} | ${ci(c.toPerson)} | ${pct(c.endToEnd)} | ${ci(n.toPerson)} | ${pct(n.endToEnd)} |`
		);
	}
}

lines.push(
	'',
	'## 5. q1 against q2, paired by row (exact two-sided sign test over the rows that changed)',
	'',
	'| corpus | question | q1 | q2 | fixed by q2 | broken by q2 | p |',
	'|---|---|---|---|---|---|---|'
);
const PAIRS: [string, string, string][] = [
	['v3', 'results-v3-q1', 'results-v3-q2'],
	['v1', 'results', 'results-v1-q2'],
	['v2', 'results-v2', 'results-v2-q2']
];
for (const [corpus, before, after] of PAIRS) {
	for (const question of ['category', 'need'] as const) {
		const test = paired(before, after, question);
		lines.push(
			`| ${corpus}${corpus === 'v3' ? ' (held out)' : corpus === 'v2' ? ' (seen)' : ''} | ${question === 'category' ? 'request' : 'need'} | ${pct(load(before).byQuestion[question].jev)} | ${pct(load(after).byQuestion[question].jev)} | ${test.fixed} | ${test.broken} | ${test.p.toFixed(4)} |`
		);
	}
}

lines.push(
	'',
	'## 6. The steer (q2 only; P(steer) ≥ 0.5 against the `steer` tag)',
	'',
	'| corpus | steer rows | recall | precision | tp / fn / fp / tn |',
	'|---|---|---|---|---|'
);
for (const { corpus, questions, r } of loaded) {
	if (questions !== 'q2' || !r.steer) continue;
	const s = r.steer;
	lines.push(
		`| ${corpus} | ${s.tp + s.fn} | ${ci(s.recall)} | ${ci(s.precision)} | ${s.tp} / ${s.fn} / ${s.fp} / ${s.tn} |`
	);
}

lines.push(
	'',
	'## 7. Through the journey (the harness experiments, run offline from the cassette)',
	''
);
for (const file of [
	'servicing-jev.experiment-result',
	'servicing-jev-v2.experiment-result',
	'servicing-jev-v3.experiment-result'
]) {
	const result = JSON.parse(readFileSync(`experiment/${file}.json`, 'utf8')) as {
		experimentId: string;
		verdict: string;
		digest: string;
		effects: {
			metricId: string;
			factor: { baseline: string; treatment: string };
			baseline: { value: number; n: number };
			treatment: { value: number; n: number };
			delta: number;
			interval: [number, number];
			underpowered?: boolean;
		}[];
	};
	lines.push(
		`**${result.experimentId}** — verdict \`${result.verdict}\`; digest \`${result.digest.slice(0, 16)}…\``,
		'',
		'| metric | treatment | baseline (regex) | treatment | Δ (95% interval) |',
		'|---|---|---|---|---|'
	);
	for (const e of result.effects) {
		const rateLike = e.metricId !== 'touches';
		const show = (v: number) => (rateLike ? `${(100 * v).toFixed(1)}%` : v.toFixed(3));
		const delta = (v: number) => (rateLike ? `${(100 * v).toFixed(1)}` : v.toFixed(3));
		lines.push(
			`| ${e.metricId} | ${e.factor.treatment} | ${show(e.baseline.value)} | ${show(e.treatment.value)} | ${delta(e.delta)} (${delta(e.interval[0])} – ${delta(e.interval[1])})${e.underpowered ? ' †' : ''} |`
		);
	}
	lines.push('');
}
lines.push(
	'† flagged underpowered by the harness’s rule (fewer than five events on a side): a ceiling artefact where the treatment barely fails.',
	'',
	'`touches` counts a classification review twice (`human:` and `escalated:`) when its answer is not the stage’s first option (`98-JEV.md` §9, finding 3); §4’s “to a person” counts reviews once.',
	'',
	'## 8. Latency and cost per run',
	'',
	'| corpus | questions | calls | p50 ms | p95 ms | max ms | mean input tokens | cost (USD) |',
	'|---|---|---|---|---|---|---|---|'
);
for (const { corpus, questions, r } of loaded) {
	lines.push(
		`| ${corpus} | ${questions} | ${r.calls} | ${r.latencyMs.p50} | ${r.latencyMs.p95} | ${r.latencyMs.max} | ${r.inputTokens.mean.toFixed(0)} | ${r.costUsd.total.toFixed(5)} |`
	);
}
const total = loaded.reduce((s, { r }) => s + r.costUsd.total, 0);
const calls = loaded.reduce((s, { r }) => s + r.calls, 0);
lines.push('', `All six runs: ${calls} calls, $${total.toFixed(4)}.`, '');

writeFileSync('experiment/SUMMARY.md', `${lines.join('\n')}\n`);
console.log(lines.join('\n'));
