"""Build the Guardrail Catalogue PDF (Axiom Verity brand) from docs/catalogue.md + descriptions.py.

  python3 build_catalogue.py   -> cover.html, body.html, _header.html, _footer.html
  python3 render_catalogue.py  -> Guardrail-Catalogue.pdf
"""
import io, re, html, pathlib, datetime
from collections import OrderedDict
from descriptions import (D, CATEGORY_INTRO, SUBCATEGORY, MATURITY, STATUS, POINTS, THREATS)

HERE = pathlib.Path(__file__).parent
# the manual's toolchain (fonts/, axiom-mark.svg, build.py): docs/manual/pdf in the repo, this folder's parent
BRAND = pathlib.Path(__import__('os').environ.get('CAB_PDF_BRAND', HERE.parent))

# ---- reuse the manual's brand block (fonts, palette, base CSS, mark) ----
src = (BRAND/'build.py').read_text(encoding='utf-8')
head = src[:src.index('\nHEADER =')]
ns = {}
exec(head.replace("ROOT = pathlib.Path('.')", f"ROOT = pathlib.Path('{BRAND}')"), ns)
CSS, MARK = ns['CSS'], ns['MARK']
NAVY, INK, MUTED, GOLD, GOLDINK, GOLDTINT, PAPER, INSET, HAIR, HAIRSTRONG = (
    ns[k] for k in ('NAVY','INK','MUTED','GOLD','GOLDINK','GOLDTINT','PAPER','INSET','HAIR','HAIRSTRONG'))

EDITION = '2026-10'
SNAPSHOT = '2 October 2026'
TODAY = datetime.date(2026, 10, 2).strftime('%-d %B %Y')

# ---- parse docs/catalogue.md ----
CAT = HERE/'catalogue.md' if (HERE/'catalogue.md').exists() else HERE.parents[2]/'catalogue.md'   # docs/catalogue.md, generated by `npm run catalogue:doc`
text = CAT.read_text(encoding='utf-8')
m = re.search(r'(\d+) entries — (\d+) shipped, (\d+) connectable, (\d+) bespoke, (\d+) blueprint, (\d+) not applicable', text)
COUNTS = dict(zip(('total','shipped','connectable','bespoke','blueprint','not-applicable'), map(int, m.groups())))

ROW = re.compile(r'^\| \*\*(?P<name>.+?)\*\* \(`(?P<id>[a-z0-9-]+)`\) — (?P<summary>.+?) \| (?P<sub>[a-z-]+) \| '
                 r'(?P<points>[^|]+?) \| (?P<maturity>[a-z-]+) \| (?P<threats>[^|]+?) \| \*\*(?P<status>[a-z-]+)\*\* — '
                 r'(?P<note>.+?) \| (?P<impl>[^|]*?) \| (?P<sources>.+?) \| (?P<review>\w+) \|$')
SRC = re.compile(r'(.+?), \*(.+?)\* \((\d{4})\)(?:; |$)')

cats = OrderedDict(); cur = None
for line in text.splitlines():
    if line.startswith('## ') and not line.startswith('## What'):
        cur = line[3:].strip(); cats[cur] = []
    elif line.startswith('| **') and cur:
        r = ROW.match(line)
        assert r, line[:80]
        e = r.groupdict()
        e['points'] = [] if e['points'].strip() == '—' else [p.strip() for p in e['points'].split(',')]
        e['threats'] = [] if e['threats'].strip() == '—' else [t.strip() for t in e['threats'].split(',')]
        e['impl'] = re.findall(r'`([^`]+)`', e['impl'])
        e['sources'] = [(pub.strip(), title.strip(), yr) for pub, title, yr in SRC.findall(e['sources'])]
        assert e['sources'], e['id']
        cats[cur].append(e)

entries = [e for es in cats.values() for e in es]
assert len(entries) == 69 and {e['id'] for e in entries} == set(D), (len(entries), set(D) ^ {e['id'] for e in entries})

def esc(s): return html.escape(s, quote=False)

# a couple of the catalogue's cross-references are file numbers a reader here cannot follow — keep them, they are the audit trail
def note_html(s):
    s = esc(s)
    s = re.sub(r'\(WP(\d+)\)$', r'<span class="wp">WP\1</span>', s.strip())
    return s

def pill(status):
    label = STATUS[status][0]
    return f'<span class="pill s-{status}">{label}</span>'

# ---- front matter ----
def legend_rows(d, keyfmt=lambda k: k):
    return ''.join(f'<tr><td class="k">{keyfmt(k)}</td><td>{esc(v if isinstance(v,str) else v[1])}</td></tr>' for k, v in d.items())

status_counts = {k: sum(1 for e in entries if e['status'] == k) for k in STATUS}
assert status_counts['shipped'] == COUNTS['shipped'] and status_counts['not-applicable'] == COUNTS['not-applicable']

front = f"""
<h1 class="first">How to read this catalogue</h1>
<p class="lede">This is the second edition of the Guardrail Catalogue that ships inside Craft A Bot: sixty-nine
techniques for governing AI agents — the first edition’s forty-five, the mechanisms the code already had
that no entry claimed, and what a bank’s control framework names that a survey of agent security does not —
gathered from the industry’s products, the standards bodies, the regulators and the research literature, and
sorted into six categories by what they do. Each entry says what the technique is
in plain terms, how mature it is, which threats it answers, and — separately and without inference — what
Craft A Bot actually does about it today.</p>

<h2>What each entry shows</h2>
<table class="legend">
<tr><td class="k">Name and id</td><td>The technique, and the identifier it has in the catalogue’s content (<code>packages/governance/src/catalogue</code>). Techniques, not vendors: the vendors and papers that ship or propose a technique are its sources.</td></tr>
<tr><td class="k">Sub-category</td><td>The finer grouping within the category — an input guardrail, an action control, a monitoring measure, and so on.</td></tr>
<tr><td class="k">Maturity</td><td>How established the technique is in practice (see below).</td></tr>
<tr><td class="k">Points</td><td>Where in the agent loop the control decides, if it decides at all. A dash means the technique is a measure, a practice or an architecture rather than a decision in the loop.</td></tr>
<tr><td class="k">Protects against</td><td>The OWASP threat codes the technique answers: <em>ASI</em> codes from the Top 10 for Agentic Applications (2026 edition), <em>LLM</em> codes from the Top 10 for LLM Applications 2025. A key is at the back.</td></tr>
<tr><td class="k">In Craft A Bot</td><td>The coverage status and the note the content carries, as of the {SNAPSHOT} snapshot, with the work package that landed it. The build refuses a status the code cannot back.</td></tr>
<tr><td class="k">Implemented by</td><td>The components or mechanisms in the product, in the code’s own words; file numbers refer to the design notes in <code>docs/design-day2/</code>.</td></tr>
<tr><td class="k">Sources</td><td>At least one standard, vendor document, paper or guidance note per entry, with publisher and year.</td></tr>
</table>

<h2>Coverage status</h2>
<p>Coverage says what the product does, not what the technique could do. The five statuses are mutually exclusive and the catalogue build (<code>checkCatalogue</code>) refuses an entry whose status does not match what it names — a <em>shipped</em> entry that names nothing, a <em>blueprint</em> that names an implementation, a <em>not applicable</em> with no reason.</p>
<table class="legend">
{''.join(f'<tr><td class="k">{pill(k)}</td><td>{esc(v[1])}</td></tr>' for k, v in STATUS.items())}
</table>
<p>In this edition: <strong>{status_counts['shipped']} shipped</strong>, {status_counts['connectable']} connectable,
<strong>{status_counts['bespoke']} bespoke</strong>, <strong>{status_counts['blueprint']} blueprint</strong>,
<strong>{status_counts['not-applicable']} not applicable</strong>. All sixty-nine entries are marked
<em>pending review</em>: the content awaits a reader’s check against its sources, and marking an entry
reviewed is a content change with a reader’s name on it, never a build step.</p>

<h2>Maturity</h2>
<table class="legend">
{''.join(f'<tr><td class="k">{esc(v[0])}</td><td>{esc(v[1])}</td></tr>' for k, v in MATURITY.items())}
</table>

<h2>Points in the loop</h2>
<table class="legend">
{''.join(f'<tr><td class="k"><code>{k}</code></td><td>{esc(v)}</td></tr>' for k, v in POINTS.items())}
</table>
"""

# ---- contents / summary table ----
n = 0
toc = ['<h1>Contents</h1>']
for cat, es in cats.items():
    toc.append(f'<h3 class="toc-cat">{esc(cat)} <span class="count">{len(es)} entries</span></h3>')
    toc.append('<table class="toc"><colgroup><col class="c1"><col class="c2"><col class="c3"><col class="c4"><col class="c5"></colgroup><thead><tr><th>#</th><th>Technique</th><th>Sub-category</th><th>Maturity</th><th>In Craft A Bot</th></tr></thead><tbody>')
    for e in es:
        n += 1; e['n'] = n
        toc.append(f'<tr><td class="n">{n:02d}</td><td>{esc(e["name"])}</td><td>{SUBCATEGORY[e["sub"]]}</td>'
                   f'<td>{MATURITY[e["maturity"]][0]}</td><td>{pill(e["status"])}</td></tr>')
    toc.append('</tbody></table>')
toc_html = '\n'.join(toc)

# ---- the entries ----
def entry_html(e):
    pts = ', '.join(f'<code>{p}</code>' for p in e['points']) if e['points'] else '<span class="dash">—</span>'
    thr = ('; '.join(f'<code>{t}</code> {esc(THREATS[t])}' for t in e['threats'])
           if e['threats'] else '<span class="dash">— (an assurance measure rather than a defence against a named threat)</span>')
    impl = ('; '.join(f'<code class="impl">{esc(i)}</code>' for i in e['impl'])) if e['impl'] else '<span class="dash">—</span>'
    srcs = ''.join(f'<li>{esc(pub)}, <em>{esc(title)}</em> ({yr}).</li>' for pub, title, yr in e['sources'])
    return f"""
<article class="entry">
  <header>
    <div class="num">{e['n']:02d}</div>
    <div class="titles"><h3>{esc(e['name'])}</h3><code class="id">{e['id']}</code></div>
    <div class="status">{pill(e['status'])}</div>
  </header>
  <div class="meta">
    <span><b>Sub-category</b> {SUBCATEGORY[e['sub']]}</span>
    <span><b>Maturity</b> {MATURITY[e['maturity']][0]}</span>
    <span><b>Points</b> {pts}</span>
  </div>
  <p class="tagline">{esc(e['summary'])}</p>
  <p class="desc">{esc(D[e['id']])}</p>
  <dl>
    <dt>Protects against</dt><dd>{thr}</dd>
    <dt>In Craft A Bot</dt><dd><span class="pill-inline s-{e['status']}">{STATUS[e['status']][0]}</span> {note_html(e['note'])}</dd>
    <dt>Implemented by</dt><dd>{impl}</dd>
    <dt>Sources</dt><dd><ul class="sources">{srcs}</ul></dd>
  </dl>
</article>"""

body = []
for cat, es in cats.items():
    body.append(f'<h1>{esc(cat)}</h1><p>{esc(CATEGORY_INTRO[cat])}</p>')
    subs = OrderedDict()
    for e in es: subs.setdefault(e['sub'], []).append(e)
    body.append('<p class="cat-sum">' + ' &nbsp;·&nbsp; '.join(f'<b>{SUBCATEGORY[s]}</b> {len(v)}' for s, v in subs.items()) + '</p>')
    for e in es:
        body.append(entry_html(e))

# ---- back matter: not claimed, threat key, bibliography ----
bp = [e for e in entries if e['status'] == 'blueprint']
na = [e for e in entries if e['status'] == 'not-applicable']
back = ['<h1>What the product does not claim</h1>',
        '<p>Two lists the catalogue keeps on purpose, so that a reader never has to infer the absence of a control.</p>',
        '<h2>Blueprint — described and mapped, nothing built</h2><ul>' +
        ''.join(f'<li><b>{esc(e["name"])}</b> — {note_html(e["note"])}</li>' for e in bp) + '</ul>',
        '<h2>Not applicable — said, with the reason</h2><ul>' +
        ''.join(f'<li><b>{esc(e["name"])}</b> — {note_html(e["note"])}</li>' for e in na) + '</ul>']

used = sorted({t for e in entries for t in e['threats']})
back.append('<h1>Threat codes</h1><p>The codes the entries cite. The ASI series is the OWASP Top 10 for Agentic Applications (2026 edition); the LLM series is the OWASP Top 10 for LLM Applications 2025. Codes not cited by any entry are listed in grey for completeness.</p>')
back.append('<table class="legend threats"><thead><tr><th>Code</th><th>Threat</th><th>Entries</th></tr></thead><tbody>')
for code, name in THREATS.items():
    hits = [e for e in entries if code in e['threats']]
    cls = '' if hits else ' class="unused"'
    back.append(f'<tr{cls}><td class="k"><code>{code}</code></td><td>{esc(name)}</td><td>{", ".join("%02d" % e["n"] for e in hits) or "—"}</td></tr>')
back.append('</tbody></table>')

bib = OrderedDict()
for e in entries:
    for pub, title, yr in e['sources']:
        bib.setdefault((pub, title, yr), []).append(e['n'])
back.append(f'<h1>Sources</h1><p>Every source the edition cites — {len(bib)} in all — with the entries that cite it. Gathered in August 2026 for the AI-safety and governance reference (<code>19-AI-SAFETY-GOVERNANCE-REFERENCE.md</code>); a URL is on the content where the reference has one.</p><ul class="bib">')
for (pub, title, yr), ns_ in sorted(bib.items(), key=lambda kv: (kv[0][0].lower(), kv[0][2])):
    back.append(f'<li>{esc(pub)}, <em>{esc(title)}</em> ({yr}). <span class="cites">Entries {", ".join("%02d" % k for k in ns_)}</span></li>')
back.append('</ul>')
back_html = '\n'.join(back)

# ---- catalogue-specific CSS ----
EXTRA = f"""
p.lede{{font-size:11.5pt;color:{MUTED};max-width:42em;line-height:1.6}}
table.legend{{font-size:9.4pt}} table.legend thead{{display:table-header-group}}
table.legend td.k{{width:24%;background:{INSET};font-weight:600;white-space:nowrap}}
table.threats td.k{{width:14%}} table.threats tr.unused td{{color:{HAIRSTRONG}}}
table.threats tr.unused td code{{color:{HAIRSTRONG}}}

.pill,.pill-inline{{display:inline-block;font-family:'IBM Plex Mono',ui-monospace,monospace;font-size:7.2pt;
  font-weight:700;letter-spacing:.09em;text-transform:uppercase;padding:.3em .55em;border-radius:.25rem;
  border:1px solid {HAIRSTRONG};white-space:nowrap;line-height:1}}
.pill-inline{{margin-right:.35em;vertical-align:baseline}}
.s-shipped{{background:{NAVY};color:#fff;border-color:{NAVY}}}
.s-connectable{{background:{GOLDTINT};color:{GOLDINK}}}
.s-bespoke{{background:{GOLDTINT};color:{GOLDINK}}}
.s-blueprint{{background:#fff;color:{MUTED}}}
.s-not-applicable{{background:{INSET};color:{MUTED};border-style:dashed}}

h3.toc-cat{{display:flex;justify-content:space-between;align-items:baseline;margin-top:1.4em}}
h3.toc-cat .count{{font-family:'IBM Plex Mono',monospace;font-size:7.4pt;letter-spacing:.08em;
  text-transform:uppercase;color:{GOLDINK};font-weight:400}}
table.toc{{font-size:9pt;margin-top:.4em;table-layout:fixed;page-break-inside:avoid;break-inside:avoid}}
table.toc col.c1{{width:6%}} table.toc col.c2{{width:46%}} table.toc col.c3{{width:20%}} table.toc col.c4{{width:14%}} table.toc col.c5{{width:14%}}
h3.toc-cat{{page-break-after:avoid;break-after:avoid}} table.toc td.n{{font-family:'IBM Plex Mono',monospace;color:{GOLDINK};width:2.2em}}
table.toc td:nth-child(2){{font-weight:600}}
p.cat-sum{{font-family:'IBM Plex Mono',monospace;font-size:7.6pt;letter-spacing:.05em;color:{MUTED};
  border-top:1px solid {HAIR};border-bottom:1px solid {HAIR};padding:.5em 0;margin:0 0 1em}}
p.cat-sum b{{color:{GOLDINK};font-weight:700}}

article.entry{{page-break-inside:avoid;break-inside:avoid;margin:0 0 1.35em;padding:0 0 1.1em;
  border-bottom:1px solid {HAIR}}}
article.entry header{{display:flex;align-items:flex-start;gap:.7em;margin:0 0 .45em}}
article.entry .num{{font-family:Newsreader,Georgia,serif;font-size:19pt;color:{GOLDINK};line-height:1;
  min-width:1.6em;padding-top:.05em}}
article.entry .titles{{flex:1}}
article.entry h3{{margin:0;font-size:13.5pt;line-height:1.15}}
article.entry code.id{{background:none;border:0;padding:0;font-size:7.6pt;color:{MUTED};letter-spacing:.02em}}
article.entry .status{{padding-top:.25em}}
article.entry .meta{{display:flex;flex-wrap:wrap;gap:.35em 1.4em;font-size:8.4pt;color:{MUTED};margin:0 0 .6em}}
article.entry .meta b{{font-family:'IBM Plex Mono',monospace;font-weight:700;font-size:6.8pt;letter-spacing:.09em;
  text-transform:uppercase;color:{GOLDINK};margin-right:.3em}}
article.entry .meta code{{font-size:.9em}}
p.tagline{{font-family:Newsreader,Georgia,serif;font-style:italic;font-size:11.2pt;color:{INK};margin:0 0 .45em;line-height:1.35}}
p.desc{{margin:0 0 .7em;max-width:46em}}
article.entry dl{{margin:0;font-size:9.1pt;display:grid;grid-template-columns:8.5em 1fr;gap:.32em .8em;align-items:start}}
article.entry dt{{font-family:'IBM Plex Mono',monospace;font-weight:700;font-size:6.9pt;letter-spacing:.09em;
  text-transform:uppercase;color:{GOLDINK};padding-top:.28em}}
article.entry dd{{margin:0}}
article.entry dd code{{font-size:.85em}}
code.impl{{white-space:normal}}
.dash{{color:{MUTED}}}
.wp{{font-family:'IBM Plex Mono',monospace;font-size:7pt;color:{MUTED};letter-spacing:.06em;margin-left:.4em}}
ul.sources{{margin:0;padding-left:1.1em;font-size:8.6pt;color:{MUTED}}} ul.sources li{{margin:.1em 0}}
ul.bib{{font-size:9pt;padding-left:1.2em}} ul.bib li{{margin:.25em 0}}
ul.bib .cites{{font-family:'IBM Plex Mono',monospace;font-size:7pt;color:{GOLDINK};letter-spacing:.04em;margin-left:.4em}}
"""

HEADER = f"""<div style="font-family:'IBM Plex Mono',monospace;font-size:6.5pt;letter-spacing:.08em;
 color:{MUTED};width:100%;padding:0 20mm;display:flex;justify-content:space-between;text-transform:uppercase;">
 <span>Craft A Bot &nbsp;·&nbsp; The Guardrail Catalogue</span><span style="color:{GOLDINK}">Axiom Verity</span></div>"""
FOOTER = f"""<div style="font-family:'IBM Plex Mono',monospace;font-size:6.5pt;letter-spacing:.08em;
 color:{MUTED};width:100%;padding:0 20mm;display:flex;justify-content:space-between;">
 <span>Edition {EDITION} &nbsp;·&nbsp; {TODAY} &nbsp;·&nbsp; PENDING REVIEW &nbsp;·&nbsp; FOR SIMULATION ONLY</span>
 <span>page <span class="pageNumber"></span> of <span class="totalPages"></span></span></div>"""

cover = f"""<div class="cover">
  <div class="top"><div class="wordmark"><span class="a">Axiom</span><span class="v">Verity</span></div></div>
  <div style="height:26mm"></div>
  <div class="mark">{MARK}</div>
  <h1 class="title">The Guardrail Catalogue</h1>
  <div class="sub">Sixty-nine techniques for governing AI agents — and what Craft&nbsp;A&nbsp;Bot does with each</div>
  <p class="lede">The second edition of the catalogue that ships inside Craft A Bot, laid out for reading:
     each technique described in plain terms, categorised by what it does, rated for maturity, mapped to
     the threats it answers, and marked — honestly — with the product’s own coverage.</p>
  <div class="spacer"></div>
  <div class="proof">∴</div>
  <div><span class="strap">EDITION {EDITION} &nbsp;·&nbsp; PENDING REVIEW</span></div>
  <div class="foot">{COUNTS['total']} entries in six categories &nbsp;·&nbsp; coverage as of {SNAPSHOT} &nbsp;·&nbsp; {TODAY} &nbsp;·&nbsp; draft for review</div>
</div>"""

def page(inner):
    return f"""<!doctype html><html><head><meta charset="utf-8"><title>Craft A Bot — The Guardrail Catalogue</title>
<style>{CSS}{EXTRA}</style></head><body>{inner}</body></html>"""

(HERE/'cover.html').write_text(page(cover), encoding='utf-8')
(HERE/'body.html').write_text(page(front + toc_html + '\n'.join(body) + back_html), encoding='utf-8')
(HERE/'_header.html').write_text(HEADER, encoding='utf-8')
(HERE/'_footer.html').write_text(FOOTER, encoding='utf-8')
print('html written:', len(entries), 'entries,', len(bib), 'sources')
