import type {
	CatalogueEntry,
	CoverageStatus,
	ExperimentResult,
	GuardrailCatalogue,
	PackRegistry,
	Stack
} from '@craftabot/core';
import {
	controlEffectiveness,
	type ControlEffectivenessHeadline
} from './control-effectiveness.js';

/** One catalogue entry's coverage as the fold reads it: its status, the registered components, the stacks that fit them, the register's effect. */
export interface CoverageRow {
	entry: CatalogueEntry;
	status: CoverageStatus;
	/** The components that implement it and are registered, in the entry's order. */
	components: string[];
	/** Registered stacks that fit one of those components. */
	stacks: string[];
	/** The register's headline effect for a control a stack carrying one of those components claims, where an experiment measured it. */
	headline?: ControlEffectivenessHeadline & { controlId: string; stackId: string };
}

/** The catalogue's counts by status and review, and the two lists the assurance pack quotes. */
export interface CoverageSummary {
	edition: string;
	entries: number;
	byStatus: Record<CoverageStatus, number>;
	reviewed: number;
	pending: number;
	/** The entries the product does *not* claim, by name — what a reviewer reads first. */
	blueprint: string[];
	notApplicable: string[];
}

const STATUSES: CoverageStatus[] = [
	'shipped',
	'connectable',
	'bespoke',
	'blueprint',
	'not-applicable'
];

/**
 * **The coverage fold** (WP98, `86-CATALOGUE.md` §5; `83-…` §6.4.3): one
 * row per catalogue entry with its status, the registered components that
 * implement it, the stacks that use them and — joined through
 * `Stack.controls` — the register's headline effect where an experiment
 * measured such a stack. The row count equals the catalogue's; the status
 * is the entry's own, since `checkCatalogue` has already verified it.
 */
export function coverageReport(
	catalogue: GuardrailCatalogue,
	registry: Pick<PackRegistry, 'getGuardrailComponent' | 'listStacks' | 'listControlMaps'>,
	results: readonly ExperimentResult[] = []
): CoverageRow[] {
	const stacks: Stack[] = registry.listStacks();
	const register =
		results.length > 0 ? controlEffectiveness(results, registry.listControlMaps()) : [];
	return catalogue.entries.map((entry) => {
		const components = (entry.coverage.componentIds ?? []).filter(
			(id) => registry.getGuardrailComponent(id) !== undefined
		);
		const using = stacks.filter((stack) =>
			stack.fit.some((fit) => components.includes(fit.componentId))
		);
		let headline: CoverageRow['headline'];
		for (const stack of using) {
			for (const controlId of stack.controls ?? []) {
				const row = register.find((entry) => entry.controlId === controlId);
				if (row?.headline && (!headline || row.headline.n > headline.n)) {
					headline = { ...row.headline, controlId, stackId: stack.id };
				}
			}
		}
		return {
			entry,
			status: entry.coverage.status,
			components,
			stacks: using.map((stack) => stack.id),
			...(headline ? { headline } : {})
		};
	});
}

/** The counts and the two lists the assurance pack's §5 quotes. */
export function coverageSummary(catalogue: GuardrailCatalogue): CoverageSummary {
	const byStatus = Object.fromEntries(STATUSES.map((status) => [status, 0])) as Record<
		CoverageStatus,
		number
	>;
	for (const entry of catalogue.entries) byStatus[entry.coverage.status] += 1;
	return {
		edition: catalogue.edition,
		entries: catalogue.entries.length,
		byStatus,
		reviewed: catalogue.entries.filter((entry) => entry.review === 'reviewed').length,
		pending: catalogue.entries.filter((entry) => entry.review === 'pending').length,
		blueprint: catalogue.entries
			.filter((entry) => entry.coverage.status === 'blueprint')
			.map((entry) => entry.name),
		notApplicable: catalogue.entries
			.filter((entry) => entry.coverage.status === 'not-applicable')
			.map((entry) => entry.name)
	};
}

const CATEGORY_TITLES: Record<CatalogueEntry['category'], string> = {
	'runtime-protection': 'Runtime protection',
	'secure-by-design': 'Secure by design',
	'identity-and-access': 'Identity and access',
	'component-hardening': 'Component hardening',
	'evaluation-and-assurance': 'Evaluation and assurance',
	'human-oversight': 'Human oversight'
};

/**
 * **`docs/catalogue.md`** (`86-…` §7): the edition as a page, generated by
 * `npm run catalogue:doc` and checked on build like `docs/metrics.md` — one
 * table per category, every entry with its status, what implements it, its
 * threats and its sources with the year. Deterministic over the content.
 */
export function renderCatalogueMarkdown(
	catalogue: GuardrailCatalogue,
	registry: Pick<PackRegistry, 'getGuardrailComponent' | 'listStacks' | 'listControlMaps'>
): string {
	const rows = coverageReport(catalogue, registry);
	const summary = coverageSummary(catalogue);
	const out: string[] = [];
	out.push('# The Guardrail Catalogue');
	out.push('');
	out.push(
		`> Generated from \`@craftabot/governance\`'s catalogue (edition ${summary.edition}) by \`npm run catalogue:doc\` (WP98, \`docs/design-day2/86-CATALOGUE.md\`). Do not edit: the build checks this page against the content. ${summary.entries} entries — ${summary.byStatus.shipped} shipped, ${summary.byStatus.connectable} connectable, ${summary.byStatus.bespoke} bespoke, ${summary.byStatus.blueprint} blueprint, ${summary.byStatus['not-applicable']} not applicable; ${summary.reviewed} reviewed, ${summary.pending} pending review.`
	);
	out.push('');
	out.push(
		'**What a status means** (tenet 28): *shipped* — a component or a mechanism exists here and the register can show what it did; *connectable* — the shell meets a vendor’s contract and a checkpoint proves it; *bespoke* — a design of record exists, built in part or as content; *blueprint* — described and mapped, nothing built; *not applicable* — said, with the reason. Nothing is implied.'
	);
	out.push('');
	for (const category of Object.keys(CATEGORY_TITLES) as CatalogueEntry['category'][]) {
		const inCategory = rows.filter((row) => row.entry.category === category);
		if (inCategory.length === 0) continue;
		out.push(`## ${CATEGORY_TITLES[category]}`);
		out.push('');
		out.push(
			'| Entry | Sub-category | Points | Maturity | Threats | Coverage | Implemented by | Sources | Review |'
		);
		out.push('|---|---|---|---|---|---|---|---|---|');
		for (const row of inCategory) {
			const e = row.entry;
			const implemented = [
				...row.components.map((id) => `\`${id}\``),
				...(e.coverage.implementedBy ?? []).map((id) => `\`${id}\``)
			];
			const sources = e.sources
				.map((source) => `${source.publisher}, *${source.title}* (${source.year})`)
				.join('; ');
			out.push(
				`| **${e.name}** (\`${e.id}\`) — ${e.summary} | ${e.subcategory} | ${e.points.length === 0 ? '—' : e.points.join(', ')} | ${e.maturity} | ${e.threats.length === 0 ? '—' : e.threats.join(', ')} | **${e.coverage.status}** — ${e.coverage.note}${e.coverage.since ? ` (${e.coverage.since})` : ''} | ${implemented.length === 0 ? '—' : implemented.join(', ')} | ${sources} | ${e.review} |`
			);
		}
		out.push('');
	}
	out.push('## What the product does not claim');
	out.push('');
	out.push(
		`- **Blueprint** (described and mapped, nothing built): ${summary.blueprint.length === 0 ? 'none' : summary.blueprint.join('; ')}.`
	);
	out.push(
		`- **Not applicable** (said, with the reason): ${summary.notApplicable.length === 0 ? 'none' : summary.notApplicable.join('; ')}.`
	);
	out.push('');
	return out.join('\n');
}
